"""Regenerate ``TRENDS.md`` from ``data/rounds.csv``.

Everything here is derived. Never hand-edit ``TRENDS.md`` -- run this instead::

    python3 scripts/trend.py

It is written to be read by a person and by ``/coach``, which is why the numbers
come with the sample size attached: a trend over four rounds is a rumour.
"""

from __future__ import annotations

import statistics
from pathlib import Path

import model
from model import COMPLETE_STATS_FROM, Round

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "TRENDS.md"

#: Below this many rounds, an R^2 is noise dressed up as a finding.
MIN_SAMPLE = 15

#: Stats worth tracking, with the direction that counts as improvement.
TRACKED = [
    ("score", "lower", "Score"),
    ("doubles_or_worse", "lower", "Doubles or worse"),
    ("gir", "higher", "Greens in regulation"),
    ("putts", "lower", "Putts"),
    ("three_putts", "lower", "Three-putts"),
    ("penalties", "lower", "Penalties"),
    ("fairways_hit", "higher", "Fairways"),
    ("up_down_pct", "higher", "Up-and-down %"),
]


def mean_of(rounds: list[Round], key: str) -> float | None:
    vals = [getattr(r, key) for r in rounds if getattr(r, key) is not None]
    return statistics.mean(vals) if vals else None


def arrow(delta: float | None, better: str) -> str:
    if delta is None or abs(delta) < 1e-9:
        return "--"
    improving = (delta < 0) if better == "lower" else (delta > 0)
    return "improving" if improving else "slipping"


def table(rows: list[list[str]], headers: list[str]) -> str:
    widths = [max(len(str(r[i])) for r in [headers] + rows) for i in range(len(headers))]
    def line(cells):
        return "| " + " | ".join(str(c).ljust(w) for c, w in zip(cells, widths)) + " |"
    out = [line(headers), "|" + "|".join("-" * (w + 2) for w in widths) + "|"]
    out += [line(r) for r in rows]
    return "\n".join(out)


def build(rounds: list[Round]) -> str:
    full = [r for r in rounds if r.is_full]
    modern = [r for r in full if r.date >= COMPLETE_STATS_FROM]
    last10, prev10 = full[-10:], full[-20:-10]

    L = []
    A = L.append
    A("# Trends")
    A("")
    A("<!-- Generated by scripts/trend.py. Do not edit by hand. -->")
    A("")
    A(f"{len(full)} complete rounds, {full[0].date} to {full[-1].date}. "
      f"{len(modern)} of them from {COMPLETE_STATS_FROM} onward, when full stat "
      f"capture began.")
    A("")

    # -- the scoring model -------------------------------------------------
    A("## What actually drives the score")
    A("")
    A("Least-squares fit of score against each stat, over every complete round:")
    A("")
    rows, thin = [], False
    for key, _, label in TRACKED[1:]:
        f = model.fit(full, key)
        if f:
            # Below this many rounds an R^2 is noise dressed as a finding.
            mark = " *" if f.n < MIN_SAMPLE else ""
            thin = thin or bool(mark)
            rows.append([label + mark, f"{f.r2:.2f}", f"{f.slope:+.2f}", str(f.n)])
    rows.sort(key=lambda r: float(r[1]), reverse=True)
    A(table(rows, ["Stat", "R^2", "Strokes per unit", "n"]))
    A("")
    if thin:
        A(f"\\* Fewer than {MIN_SAMPLE} rounds. Penalties, three-putts and "
          f"up-and-down were only logged from {COMPLETE_STATS_FROM}, so their "
          f"R^2 is suggestive, not established.")
        A("")
    f = model.fit(full)
    if f:
        A(f"**{f}**")
        A("")
        A(f"Doubles explain {f.r2:.0%} of the variance in his scoring; greens in "
          f"regulation explain less, and putts and fairways explain almost "
          f"nothing. Each disaster hole costs about {f.slope:.1f} strokes. "
          f"A round with zero of them projects to {f.intercept:.0f}.")
        A("")

    # -- the round underneath ---------------------------------------------
    A("## The round underneath")
    A("")
    A("Every double-or-worse hole replayed as a bogey. Bogeys, missed greens and "
      "three-putts all still count -- this only strips the damage past bogey.")
    A("")
    rows = []
    for r in full[-10:]:
        u = r.round_underneath
        rows.append([r.date, r.course[:24], str(r.score),
                     str(r.doubles_or_worse if r.doubles_or_worse is not None else "-"),
                     str(u if u is not None else "-"),
                     f"{r.score - u:+d}" if u is not None else "-"])
    A(table(rows, ["Date", "Course", "Score", "Doubles", "Underneath", "Tax"]))
    A("")
    tax = [r.score - r.round_underneath for r in full[-10:]
           if r.round_underneath is not None]
    if tax:
        A(f"Disaster tax over the last {len(tax)} rounds: "
          f"**{statistics.mean(tax):.1f} strokes per round**.")
        A("")

    # -- trend table -------------------------------------------------------
    A("## Last 10 rounds vs the 10 before")
    A("")
    rows = []
    for key, better, label in TRACKED:
        a, b = mean_of(last10, key), mean_of(prev10, key)
        if a is None:
            continue
        delta = (a - b) if b is not None else None
        rows.append([
            label,
            f"{a:.1f}",
            f"{b:.1f}" if b is not None else "-",
            f"{delta:+.1f}" if delta is not None else "-",
            arrow(delta, better),
        ])
    A(table(rows, ["Stat", "Last 10", "Prior 10", "Change", "Direction"]))
    A("")

    # -- misses ------------------------------------------------------------
    bias = model.miss_bias(full, 10)
    A("## Where the misses go")
    A("")
    A(table(
        [["Tee shots", f"left {bias['tee_left']}", f"right {bias['tee_right']}"],
         ["Approaches", f"short {bias['approach_short']}", f"long {bias['approach_long']}"]],
        ["", "Miss A", "Miss B"]))
    A("")
    if bias["approach_short"] > 2 * max(bias["approach_long"], 1):
        A(f"Approaches miss short {bias['approach_short']} times to "
          f"{bias['approach_long']} long. This is the data behind **one more "
          f"club** -- the miss is almost never long.")
        A("")

    # -- working range -----------------------------------------------------
    fc = model.floor_ceiling(full, 10)
    if fc:
        A("## Working range")
        A("")
        A(f"- **Ceiling:** {fc['ceiling']}")
        A(f"- **Typical:** {fc['typical']:.0f} (median of last {fc['n']})")
        A(f"- **Floor:** {fc['floor']}")
        A("")
        lo, mid, hi = model.predict_score(full[-20:], 2)
        A(f"With two doubles instead of the recent average, the model projects "
          f"**{lo:.0f}-{hi:.0f}**, centred on {mid:.0f}.")
        A("")

    A("## Every round with complete stats")
    A("")
    rows = [[r.date, r.course[:22], str(r.score),
             str(r.doubles_or_worse if r.doubles_or_worse is not None else "-"),
             str(r.gir if r.gir is not None else "-"),
             str(r.putts if r.putts is not None else "-"),
             str(r.penalties if r.penalties is not None else "-")]
            for r in modern]
    A(table(rows, ["Date", "Course", "Score", "Dbl+", "GIR", "Putts", "Pen"]))
    A("")
    return "\n".join(L)


def main() -> int:
    rounds = model.load()
    OUT.write_text(build(rounds) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} from {len(rounds)} rounds")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
